version: '3.7'

services:
    # db:
    #     image: postgres:12
    #     restart: on-failure
    #     environment:
    #         POSTGRES_PASSWORD: password
    #         POSTGRES_USER: user
    #         POSTGRES_DB: db
    #     ports:
    #         - 80:80
    #     # volumes:
    #     #     - db_data:/var/lib/postgresql/data

    backend:
        build:
          context: ./backend
        image: backend
        ports:
          - 3001:3001
        restart: on-failure
    
    frontend:
        build:
          context: ./frontend
        image: frontend
        ports:
          - 3000:3000
        restart: on-failure
        