version: '3.7'

services:
    db:
        image: postgres:12
        restart: always
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_NAME=${POSTGRES_NAME}
          - POSTGRES_DB=${POSTGRES_DB}

        ports:
            - '5432:5432'
        volumes:
            - postgres:/var/lib/postgresql/data

    backend:
        build:
          context: ./backend
        image: backend
        ports:
          - 3001:3001
        restart: on-failure
    
    frontend:
        build:
          context: ./frontend
        image: frontend
        ports:
          - 3000:3000
        restart: on-failure

volumes:
  postgres:

